### ISSUE TITLE
Improve language support

### ISSUE THREAD

**Issue by lfaucon** [vood00child/tama#2]
Do some research about what are good ways to add language support in the app, then implement French/English version. German later.

**Comment by vood00child** [comment]
For this I use react-intl. BabelEdit and babel-plugin-react-intl are used to easily manage the translation files. Executing 'npm run translate' starts babel and extracts the message IDs from the source files to store them to build/messages. Then BabelEdit loads these ids as well as the translations files so that they're easily editable. See https://www.codeandweb.com/babeledit/tutorials/how-to-translate-your-react-app-with-react-intl for more details. React-intl documentation at https://github.com/yahoo/react-intl

**Comment by lfaucon** [comment]
Great!
